# Generated by Django 5.1a1 on 2024-06-24 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news_post',
            options={'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AddField(
            model_name='news_post',
            name='user_name',
            field=models.TextField(default='user', max_length=100, verbose_name='Автор'),
            preserve_default=False,
        ),
    ]
